# -*- coding: utf-8 -*-
"""PDF_Editor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vedeb9RjnjK5Ggubv3lytUT4P9NIhP4X
"""

pip install streamlit
pip install langchain
pip install langchain-community
pip install langchain-openai
pip install chromadb
pip install pypdf
pip install sentence-transformers
pip install faiss-cpu
pip install pyinstaller
import os
import tempfile
import streamlit as st

from langchain_community.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

from langchain_openai import ChatOpenAI
from langchain.chains import RetrievalQA

OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"

st.title("PDF AI Chatbot")

uploaded_files = st.file_uploader(
    "Upload PDF Files",
    type=["pdf"],
    accept_multiple_files=True
)

if uploaded_files:

    all_docs = []

    for uploaded_file in uploaded_files:

        with tempfile.NamedTemporaryFile(delete=False) as tmp:
            tmp.write(uploaded_file.read())
            pdf_path = tmp.name

        loader = PyPDFLoader(pdf_path)
        docs = loader.load()
        all_docs.extend(docs)

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200
    )

    chunks = splitter.split_documents(all_docs)

    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )

    vectorstore = Chroma.from_documents(
        documents=chunks,
        embedding=embeddings,
        persist_directory="chroma_db"
    )

    retriever = vectorstore.as_retriever(search_kwargs={"k": 4})

    llm = ChatOpenAI(
        model="gpt-4o-mini",
        api_key=OPENAI_API_KEY,
        temperature=0
    )

    qa_chain = RetrievalQA.from_chain_type(
        llm=llm,
        retriever=retriever,
        return_source_documents=True
    )

    query = st.text_input("Ask a question")

    if query:

        result = qa_chain({"query": query})

        st.subheader("Answer")
        st.write(result["result"])

        st.subheader("Sources")

        for doc in result["source_documents"]:
            page = doc.metadata.get("page", "Unknown")
            st.write(f"Page: {page + 1}")
            st.write(doc.page_content[:500])
            st.divider()
streamlit run app.py

os.system("streamlit run app.py")

pyinstaller --onefile launcher.py